In [1]:
import numpy as np #numpy library used for working with arrays.

one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

std1 = np.array([22, 21, 28, 29, 47, 10])
print(std1)                                    #examples of creating one dimensional array

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]
[22 21 28 29 47 10]


In [2]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

std2 = np.array([[11, 22], [33, 44], [55, 66],[77, 88] , [99, 0]])
print(std2)                                   #examples of creating two dimensional array

[[ 6  5]
 [11  7]
 [ 4  8]]
[[11 22]
 [33 44]
 [55 66]
 [77 88]
 [99  0]]


In [3]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

std3 = np.arange(1, 101)
print(std3)                                   #its an array of returning numbers between specified values (1 to 100)

[ 5  6  7  8  9 10 11]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [4]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100) 

std4 = np.random.randint(low=1, high=3, size=(30))
print(std4)                                   #giving values with an array that starts 1 until 3


[64 99 78 91 87 89]
[1 2 2 2 1 2 2 1 1 2 1 2 1 1 1 1 1 1 2 1 1 1 2 1 2 1 1 1 1 2]


In [5]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

std5 = np.random.random([10])
print(std5)                                   #random.random gives random values just between 0 to 1

[0.40278997 0.94760386 0.7588702  0.42713482 0.67621143 0.55822638]
[0.72843011 0.48036534 0.38639531 0.15817668 0.8070929  0.35283454
 0.00677669 0.54502903 0.85795847 0.13132425]


In [6]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3) 

std6=np.random.uniform(low=0.0, high=1.0, size=3)+10.0
print(std6)                                  #np.random.uniform making same thing with pass example


[2.40278997 2.94760386 2.7588702  2.42713482 2.67621143 2.55822638]
[10.82475384 10.75049341 10.7986594 ]


In [7]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

std7=np.random.randint(5, size=5)
print(std7)                                 #np.random.randint returns integer values 0 to 5 with 1x5 array
           
std8=np.random.randint(10, size=(3, 3))
print(std8)                                 #np.random.randint returns integer values 0 to 2 with 3x3 array

[192 297 234 273 261 267]
[0 2 3 2 3]
[[7 5 0]
 [3 2 7]
 [7 1 8]]


In [9]:
feature = np.arange(6, 21)                  #examples of arithmetic operations 
print(feature)
label = (feature * 3) + 4
print(label)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [10]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-0.75197587  0.46765356  0.05887356 -0.17996653  0.13398686 -0.98949241
 -1.4324217  -0.09140766  0.5513962  -0.13711785  1.87570512  0.23572355
 -1.78122731 -1.45439272  1.43309105]
[21.24802413 25.46765356 28.05887356 30.82003347 34.13398686 36.01050759
 38.5675783  42.90859234 46.5513962  48.86288215 53.87570512 55.23572355
 56.21877269 59.54560728 65.43309105]
